const products = [
  // Birthday
  {
    id: 1,
    event: "Birthday",
    theme: "Circus",
    name: "Circus Balloons",
    price: 10,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=1',
  },
  {
    id: 2,
    event: "Birthday",
    theme: "Circus",
    name: "Circus Party Hats",
    price: 5,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=2',
  },
  {
    id: 3,
    event: "Birthday",
    theme: "Circus",
    name: "Clown Decorations",
    price: 12,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=3',
  },
  {
    id: 4,
    event: "Birthday",
    theme: "Circus",
    name: "Circus Themed Tableware",
    price: 8,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=4',
  },

  {
    id: 5,
    event: "Birthday",
    theme: "Princess",
    name: "Princess Cake Toppers",
    price: 15,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=5',
  },
  {
    id: 6,
    event: "Birthday",
    theme: "Princess",
    name: "Princess Balloons",
    price: 10,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=6',
  },
  {
    id: 7,
    event: "Birthday",
    theme: "Princess",
    name: "Princess Banner",
    price: 12,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=7',
  },
  {
    id: 8,
    event: "Birthday",
    theme: "Princess",
    name: "Princess Tableware",
    price: 8,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=8',
  },

  {
    id: 9,
    event: "Birthday",
    theme: "Space",
    name: "Space-Themed Plates",
    price: 5,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=9',
  },
  {
    id: 10,
    event: "Birthday",
    theme: "Space",
    name: "Space Rocket Balloons",
    price: 8,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=10',
  },
  {
    id: 11,
    event: "Birthday",
    theme: "Space",
    name: "Planet Decor",
    price: 12,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=11',
  },
  {
    id: 12,
    event: "Birthday",
    theme: "Space",
    name: "Space Party Hats",
    price: 5,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=12',
  },

  {
    id: 13,
    event: "Birthday",
    theme: "Gaming",
    name: "Gaming Controllers Decoration",
    price: 12,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=13',
  },
  {
    id: 14,
    event: "Birthday",
    theme: "Gaming",
    name: "Video Game Themed Cupcakes",
    price: 15,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=14',
  },
  {
    id: 15,
    event: "Birthday",
    theme: "Gaming",
    name: "Retro Gaming Posters",
    price: 8,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=15',
  },
  {
    id: 16,
    event: "Birthday",
    theme: "Gaming",
    name: "Gaming Chair Cushion",
    price: 20,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=16',
  },

  // Wedding
  {
    id: 17,
    event: "Wedding",
    theme: "Fairy Tale",
    name: "Fairy Tale Wedding Cake",
    price: 50,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=17',
  },
  {
    id: 18,
    event: "Wedding",
    theme: "Fairy Tale",
    name: "Fairy Tale Wedding Invitations",
    price: 15,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=18',
  },
  {
    id: 19,
    event: "Wedding",
    theme: "Fairy Tale",
    name: "Fairy Tale Themed Cake Topper",
    price: 25,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=19',
  },
  {
    id: 20,
    event: "Wedding",
    theme: "Fairy Tale",
    name: "Fairy Tale Chair Decor",
    price: 30,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=20',
  },

  {
    id: 21,
    event: "Wedding",
    theme: "Romantic",
    name: "Romantic Wedding Bouquet",
    price: 20,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=21',
  },
  {
    id: 22,
    event: "Wedding",
    theme: "Romantic",
    name: "Romantic Table Settings",
    price: 15,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=22',
  },
  {
    id: 23,
    event: "Wedding",
    theme: "Romantic",
    name: "Romantic Chair Covers",
    price: 18,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=23',
  },
  {
    id: 24,
    event: "Wedding",
    theme: "Romantic",
    name: "Romantic Candle Holders",
    price: 12,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=24',
  },

  // Corporate Event
  {
    id: 25,
    event: "Corporate Event",
    theme: "Modern",
    name: "Modern Business Cards",
    price: 25,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=25',
  },
  {
    id: 26,
    event: "Corporate Event",
    theme: "Modern",
    name: "Conference Tablecloth",
    price: 15,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=26',
  },
  {
    id: 27,
    event: "Corporate Event",
    theme: "Modern",
    name: "Tech Presentation Kit",
    price: 30,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=27',
  },
  {
    id: 28,
    event: "Corporate Event",
    theme: "Modern",
    name: "Modern Keychains",
    price: 5,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=28',
  },

  {
    id: 29,
    event: "Corporate Event",
    theme: "Professional",
    name: "Professional Pen Set",
    price: 10,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=29',
  },
  {
    id: 30,
    event: "Corporate Event",
    theme: "Professional",
    name: "Lanyards for Event Passes",
    price: 8,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=30',
  },
  {
    id: 31,
    event: "Corporate Event",
    theme: "Professional",
    name: "Corporate Swag Bags",
    price: 12,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=31',
  },
  {
    id: 32,
    event: "Corporate Event",
    theme: "Professional",
    name: "Business Event Banners",
    price: 20,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=32',
  },

  // Festival
  {
    id: 33,
    event: "Festival",
    theme: "Carnival",
    name: "Carnival Mask",
    price: 10,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=33',
  },
  {
    id: 34,
    event: "Festival",
    theme: "Carnival",
    name: "Carnival Streamers",
    price: 5,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=34',
  },
  {
    id: 35,
    event: "Festival",
    theme: "Carnival",
    name: "Carnival Party Hats",
    price: 7,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=35',
  },
  {
    id: 36,
    event: "Festival",
    theme: "Carnival",
    name: "Carnival Balloons",
    price: 8,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=36',
  },

  {
    id: 37,
    event: "Festival",
    theme: "Music",
    name: "Music Festival Tickets",
    price: 100,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=37',
  },
  {
    id: 38,
    event: "Festival",
    theme: "Music",
    name: "Music Stage Backdrop",
    price: 150,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=38',
  },
  {
    id: 39,
    event: "Festival",
    theme: "Music",
    name: "Musical Instruments Decoration",
    price: 12,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=39',
  },
  {
    id: 40,
    event: "Festival",
    theme: "Music",
    name: "Music Festival T-shirts",
    price: 25,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=40',
  },

  {
    id: 41,
    event: "Festival",
    theme: "Light Show",
    name: "Light Show Projector",
    price: 50,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=41',
  },
  {
    id: 42,
    event: "Festival",
    theme: "Light Show",
    name: "Glow-in-the-Dark Decorations",
    price: 10,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=42',
  },
  {
    id: 43,
    event: "Festival",
    theme: "Light Show",
    name: "Light-up Balloons",
    price: 15,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=43',
  },
  {
    id: 44,
    event: "Festival",
    theme: "Light Show",
    name: "LED Light Strings",
    price: 20,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=44',
  },

  {
    id: 45,
    event: "Festival",
    theme: "Cultural",
    name: "Cultural Dance Costume",
    price: 35,
    popularity: 7,
    image: 'https://picsum.photos/200/300?random=45',
  },
  {
    id: 46,
    event: "Festival",
    theme: "Cultural",
    name: "Cultural Food Stall",
    price: 40,
    popularity: 6,
    image: 'https://picsum.photos/200/300?random=46',
  },
  {
    id: 47,
    event: "Festival",
    theme: "Cultural",
    name: "Cultural Event Stage Decor",
    price: 60,
    popularity: 8,
    image: 'https://picsum.photos/200/300?random=47',
  },
  {
    id: 48,
    event: "Festival",
    theme: "Cultural",
    name: "Cultural Art Display",
    price: 25,
    popularity: 9,
    image: 'https://picsum.photos/200/300?random=48',
  },

];

export default products;
